sudo: false

language: python
python:
- 2.7
- 3.4

cache: pip

env:
  global:
  - RANDOM_SEED=12345

install:
- pip install coveralls scrutinizer-ocular

before_script:
- pip install -r requirements.txt

script:
- python manage.py test

after_success:
- coveralls
- ocular

notifications:
  email:
    on_success: never
    on_failure: change
